systemd:
  units:
    - name: wireguard-install.service
      enabled: true
      contents: |
        [Unit]
        Description=Setup WireGuard
        After=network.target

        [Service]
        Type=oneshot
        ExecStart=/etc/wireguard-setup
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target


    - name: wireguard-module.service
      enabled: true
      contents: |
        [Unit]
        Description=WireGuard module loading

        Before=network-pre.target
        Wants=network-pre.target

        DefaultDependencies=no

        Requires=torcx.target local-fs.target
        After=torcx.target local-fs.target

        [Service]
        Type=oneshot
        EnvironmentFile=/run/metadata/torcx
        ExecStartPre=-/sbin/modprobe ip6_udp_tunnel
        ExecStartPre=-/sbin/modprobe udp_tunnel
        ExecStart=-/sbin/insmod ${TORCX_UNPACKDIR}/WireGuard/lib/modules/%v/extra/wireguard.ko
        RemainAfterExit=yes

        [Install]
        WantedBy=network.target


storage:
  files:
    - filesystem: "root"
      path:       "/etc/wireguard-setup"
      mode:       0500
      contents:
        inline: |
          #!/bin/bash
          set -ex

          source /etc/os-release

          PKG="/var/lib/torcx/store/${VERSION_ID}/WireGuard:CoreOS_${VERSION_ID}.torcx.tgz"
          if [ -f "${PKG}" ]
          then
            exit 0
          fi

          mkdir -p "/var/lib/torcx/store/${VERSION_ID}"
          wget https://github.com/miguelangel-nubla/WireGuard-CoreOS/releases/download/latest-all/WireGuard.CoreOS_${VERSION_ID}.torcx.tgz -O "${PKG}"
          jq '.value.images += [{ "name": "WireGuard", "reference": "'CoreOS_${VERSION_ID}'" }]' /usr/share/torcx/profiles/vendor.json > /etc/torcx/profiles/wg.json
          echo wg > /etc/torcx/next-profile

          reboot

    - filesystem: "root"
      path:       "/etc/profile.d/torcx-path.sh"
      mode:       0400
      contents:
        inline: |
          export PATH="/var/run/torcx/bin:${PATH}"
